title: "n4ma Demonstrator"
description: "Demonstration of Linked Data queries for the n4ma project."
author: "Andra Waagmeester & Josh Moore"

theme: minima

# markdown: kramdown
# remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-datapage-generator

exclude:
  - sparql.md


# Doesn't work on GitHub Pages
page_gen-dirs: true
page_gen:
- data: cultivars
  template: sparql.rq
  dir: sparql/cultivars
  index_files: true
  extension: .rq
- data: pubrecord
  template: sparql.rq
  dir: sparql/pubrecord
  index_files: true
  extension: .rq
- data: climate_change
  template: sparql.rq
  dir: sparql/climate_change
  index_files: true
  extension: .rq
